apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv0001
spec:
  storageClassName: manual
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce # Only a single node can read/write
  resources:
    requests:
      storage: 1Gi